// Generated by tools/contributors.py, please do not update manually.
package org.futo.inputmethod.latin.uix.settings.pages.credits

@Suppress("HardCodedStringLiteral")
val languageContribs: List<String> = listOf(
    "LucasMZ (pt-BR)",
    "Witek (pl)",
    "abb128 (lt, ru)",
    "zvonimir (hr)"
)

@Suppress("HardCodedStringLiteral")
val layoutContribs: List<String> = listOf(
    "BoFFire",
    "DanielBreiner",
    "IliyanKostov9",
    "Imold",
    "Midnight1938",
    "NicolasLagaillardie",
    "RHJihan",
    "Zvonimir-FUTO",
    "abdelhaqueidali",
    "chrisnordborg",
    "hipi66",
    "lomtjjz",
    "pjrobertson",
    "sapradhan",
    "slycordinator",
    "tenextractor"
)

@Suppress("HardCodedStringLiteral")
val codeContribs: List<String> = listOf(
    "Adolar0042",
    "arbitrary-dev",
    "barmiro",
    "ornstrange",
    "ravarage",
    "remreren",
    "roguesensei",
    "s-h-a-d-o-w",
    "sapradhan",
    "tenextractor",
    "venkatesh2090"
)
