// Generated by tools/contributors.py, please do not update manually.
package org.futo.inputmethod.latin.uix.settings.pages.credits

@Suppress("HardCodedStringLiteral")
val languageContribs: List<String> = listOf(
    "Ahmet Çeliker (tr)",
    "Andreas (sv-SE)",
    "DanielSong (zh-CN)",
    "Edoardo Andrei Morosanu (it)",
    "Fjuro (cs)",
    "Igor (uk)",
    "J.Carver (fr)",
    "JustADeer (id)",
    "LaubeQ (es-AR)",
    "LucasMZ (pt-BR)",
    "MP (es-ES)",
    "Nai (kk)",
    "Natan (pt-BR)",
    "Nero (es)",
    "Phoenix_R49 (fr)",
    "RubberhoseCrypto (ro)",
    "Rune (da)",
    "Stefan (sr-Latn)",
    "TheBlunius (pl)",
    "TurtleBear (ja)",
    "WertZuz (de)",
    "Witek (pl)",
    "abb128 (lt, ru)",
    "abcerenbicki (tr)",
    "anonutz (de)",
    "dagfen15+github (es-MX)",
    "enlil.baal (fr)",
    "haralds.bukavs (lv)",
    "indimio (el)",
    "jonweblin2205 (uk)",
    "kiara (ja)",
    "moishi67 (he)",
    "rihvast (et)",
    "ron (de)",
    "simonp203 (nb-NO)",
    "warnly (ja)",
    "zvonimir (hr)",
    "川音리오@KawaneRio (ja)"
)

@Suppress("HardCodedStringLiteral")
val layoutContribs: List<String> = listOf(
    "BoFFire",
    "DanielBreiner",
    "DeepNestedSpider",
    "IliyanKostov9",
    "Imold",
    "Midnight1938",
    "NicolasLagaillardie",
    "RHJihan",
    "SanmayJoshi",
    "Zvonimir-FUTO",
    "abdelhaqueidali",
    "chrisnordborg",
    "hipi66",
    "lomtjjz",
    "pjrobertson",
    "sapradhan",
    "slycordinator",
    "tenextractor"
)

@Suppress("HardCodedStringLiteral")
val codeContribs: List<String> = listOf(
    "Adolar0042",
    "arbitrary-dev",
    "barmiro",
    "ornstrange",
    "ravarage",
    "remreren",
    "roguesensei",
    "s-h-a-d-o-w",
    "sapradhan",
    "tenextractor",
    "venkatesh2090"
)
