package org.futo.inputmethod.event.combiners.vietnamese

/** Vietnamese tone marks.
 *
 * Represents the five tone marks used in Vietnamese writing system.
 */
enum class ToneMark(val map: Map<Char, Char>) {
    /** Dấu sắc (acute accent) - rising tone */
    ACUTE(mapOf(
        'a' to 'á',
        'â' to 'ấ',
        'ă' to 'ắ',
        'e' to 'é',
        'ê' to 'ế',
        'i' to 'í',
        'o' to 'ó',
        'ô' to 'ố',
        'ơ' to 'ớ',
        'u' to 'ú',
        'ư' to 'ứ',
        'y' to 'ý',
        // uppercase
        'A' to 'Á',
        'Â' to 'Ấ',
        'Ă' to 'Ắ',
        'E' to 'É',
        'Ê' to 'Ế',
        'I' to 'Í',
        'O' to 'Ó',
        'Ô' to 'Ố',
        'Ơ' to 'Ớ',
        'U' to 'Ú',
        'Ư' to 'Ứ',
        'Y' to 'Ý',
    )),
    /** Dấu huyền (grave accent) - falling tone */
    GRAVE(mapOf(
        'a' to 'à',
        'â' to 'ầ',
        'ă' to 'ằ',
        'e' to 'è',
        'ê' to 'ề',
        'i' to 'ì',
        'o' to 'ò',
        'ô' to 'ồ',
        'ơ' to 'ờ',
        'u' to 'ù',
        'ư' to 'ừ',
        'y' to 'ỳ',
        // uppercase
        'A' to 'À',
        'Â' to 'Ầ',
        'Ă' to 'Ằ',
        'E' to 'È',
        'Ê' to 'Ề',
        'I' to 'Ì',
        'O' to 'Ò',
        'Ô' to 'Ồ',
        'Ơ' to 'Ờ',
        'U' to 'Ù',
        'Ư' to 'Ừ',
        'Y' to 'Ỳ',
    )),
    /** Dấu hỏi (hook above) - dipping tone */
    HOOK(mapOf(
        'a' to 'ả',
        'â' to 'ẩ',
        'ă' to 'ẳ',
        'e' to 'ẻ',
        'ê' to 'ể',
        'i' to 'ỉ',
        'o' to 'ỏ',
        'ô' to 'ổ',
        'ơ' to 'ở',
        'u' to 'ủ',
        'ư' to 'ử',
        'y' to 'ỷ',
        // uppercase
        'A' to 'Ả',
        'Ă' to 'Ẳ',
        'Â' to 'Ẩ',
        'E' to 'Ẻ',
        'Ê' to 'Ể',
        'O' to 'Ỏ',
        'Ô' to 'Ổ',
        'Ơ' to 'Ở',
        'I' to 'Ỉ',
        'U' to 'Ủ',
        'Ư' to 'Ử',
        'Y' to 'Ỷ',
    )),
    /** Dấu ngã (tilde) - creaky rising tone */
    TILDE(mapOf(
        'a' to 'ã',
        'ă' to 'ẵ',
        'â' to 'ẫ',
        'e' to 'ẽ',
        'ê' to 'ễ',
        'o' to 'õ',
        'ô' to 'ỗ',
        'ơ' to 'ỡ',
        'i' to 'ĩ',
        'u' to 'ũ',
        'ư' to 'ữ',
        'y' to 'ỹ',
        // uppercase
        'A' to 'Ã',
        'Ă' to 'Ẵ',
        'Â' to 'Ẫ',
        'E' to 'Ẽ',
        'Ê' to 'Ễ',
        'O' to 'Õ',
        'Ô' to 'Ỗ',
        'Ơ' to 'Ỡ',
        'I' to 'Ĩ',
        'U' to 'Ũ',
        'Ư' to 'Ữ',
        'Y' to 'Ỹ',
    )),
    /** Dấu nặng (dot below) - creaky falling tone */
    DOT(mapOf(
        'a' to 'ạ',
        'ă' to 'ặ',
        'â' to 'ậ',
        'e' to 'ẹ',
        'ê' to 'ệ',
        'o' to 'ọ',
        'ô' to 'ộ',
        'ơ' to 'ợ',
        'i' to 'ị',
        'u' to 'ụ',
        'ư' to 'ự',
        'y' to 'ỵ',
        // uppercase
        'A' to 'Ạ',
        'Ă' to 'Ặ',
        'Â' to 'Ậ',
        'E' to 'Ẹ',
        'Ê' to 'Ệ',
        'O' to 'Ọ',
        'Ô' to 'Ộ',
        'Ơ' to 'Ợ',
        'I' to 'Ị',
        'U' to 'Ụ',
        'Ư' to 'Ự',
        'Y' to 'Ỵ',
    )),
}
