name: Build APK

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up signing configs
        if: env.KEYSTORE_FILE != ''
        run: ./setUpPropertiesCI.sh
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          CRASHREPORTING_FILE: ${{ secrets.CRASHREPORTING_FILE }}

      - name: Build APK
        run: ./gradlew assemblePlaystoreRelease


      - name: List APK outputs
        run: ls -lhR build/outputs/apk
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: keyboard-apk
          path: build/outputs/apk/**/*.apk
          

